meta_product_name: "Instastronaut"
meta_title: "Instastronaut - Get famous now"
meta_description: "Don't wait months to make your brand famous. Buy an Instagram account and start selling now."
meta_image: "banner.jpg" # should exist in `app/assets/images/`
twitter_account: "@instastronaut"   # required for Twitter Cards
